### ISSUE TITLE
[Meta] - v2

### ISSUE THREAD

**Issue by anilcse** [vitwit/resolute#1077]
The following are highlevel features for v2

- [ ] **Validator Profile**
    - [ ] List all the networks the validator validates on (Ranks on each network by voting power, governance activity, uptime, commission, proposed blocks etc)
    - [ ] Notices (Hisotry of jailed/unjailed/inactive, change commissions, missed gov votes, missed upgrades)
    - [ ] Allow delegators to perform staking actions, governance vote override
    - [ ] Allow delegators to message to the validators directly (+responses)
    
- [ ] **Multi-wallet portfolio**
    - [ ] Allow users to connect multiple wallets to track portfolio (Should we restrict to verify via message signing?)
    - [ ] Selected account acts as the main account
    
- [ ] **Multi-wallet interactions**
    - [ ] Single click restake/claim on multiple wallets powered by authz

- [ ] **Airdrop claim page**
    - [ ] All airdrops (if not gamified with special cases)
    - [ ] Airdrop claims for multisig wallets

- [ ] **Portfolio Dashboard**
    - [ ] List/Chart time vs portfolio value (for single/multi accounts)
    - [ ] Export transactions for taxation

- [ ] **Alerts**
    - [ ] Events: Balance change, stake, gov transactions
    - [ ] NFT sale/bid alerts
    - [ ] DeFi on order/position fulfilment
    
- [ ] **Transaction Builder**
    - [ ] Multi-message transaction builder
    - [ ] Transaction re-try from history
    
- [ ] **Search**
    - [ ] Accounts, transactions, NFTs, Blocks

- [ ] **Smart contracts**
    - [ ] Contract Dashboard
    - [ ] Read & Write: Intelligent transaction message builder for users to interact with smart contracts (no code-snippet kind)
    - [ ] Code, Compiler, Bugs suggestions, Verified
    - [ ] Clone on testnet (Export and deploy on a testnet)

- [ ] **NFT world**
    - [ ] NFT dashboard
    - [ ] Explore
    - [ ] Buy/Sell
    
- [ ] **Interchain swaps**
    - [ ] Single click swaps via Squidrouter
    
- [ ] **Groups (?)**
    - [ ]
