### ISSUE TITLE
Current Sprint

### ISSUE THREAD

**Issue by charymalloju** [vitwit/resolute#1183]
- [x] **Interchain swaps**
    - [x] Single click swaps via Squidrouter

- [x] **Transaction Builder**
    - [x] Multi-message transaction builder
    - [x] Transaction re-try from history
- [x] **Validator Profile**
    - [ ] List all the networks the validator validates on (Ranks on each network by voting power, governance activity, uptime, commission, proposed blocks etc)
- [x] #1223
    - [x] deploy, query, execute
