### ISSUE TITLE
group: manual testing issues

### ISSUE THREAD

**Issue by aleem1314** [vitwit/resolute#555]
# Summary

- [x] Disable create button and display loading icon during group creation. @aleem1314  #544 
- [x] Populate current user address and add members section on the create group page. @aleem1314 #544 
- [x] Add copy to clipboard option for group member addresses in the group details page. @aleem1314 #544 
- [x] Update the Decision Policies section in the group details page to show percentages in the range of 0-100% instead of 0.0-1%.@aleem1314 #563 
- [x] Align the Min Exec period and its title properly in the Decision Policies section of the group details page.@aleem1314 #563 
- [x] Display the execution period and voting period in days instead of seconds in the Decision Policies section of the group details page.@aleem1314 #563 .
- [x] Display the execution period and voting period in days instead of seconds in the Decision Policy details page. @aleem1314 #564  
- [x] Remove `Type` `Group ID` and `Version` `Threshold` from Decision Policy details page. @aleem1314 #564
- [x] Rename `Percentage` to `Quorum`, and if policy type is `Threshold` calculate percentage with `threshold/group_total_weight` in Decision Policy details page. @aleem1314  #564 
- [x] Rename `Admin` to policy address in Decision Policy details page. @aleem1314  #564
- [x] Remove `Description` title. Just display description if present  in Decision Policy details page. @aleem1314  #564
- [x] Remove `metadata` field and add following fields while submitting a new proposal https://docs.cosmos.network/main/modules/group#proposal-4. #583 
- [x] Set default voting period as `2weeks` and minimum execution period to `1week`.
- [x] Remove `update` button elevation in update policy section on the policy details page. #583 
- [x] Remove update button elevation in the `Update Policy Metadata` section. 
- [x] Display all fields, if present, in the proposal details page according to the specification found at https://docs.cosmos.network/main/modules/group#proposal-4. #583 
- [x]  Show the current voting and expected quorum percentage in the proposal details page.
- [x] If no group member voted on the proposal, display "No one voted" message. #583 
- [x] In vote dialog add `justification` field https://docs.cosmos.network/main/modules/group#vote-2. #583 
- [x] Rename `metadata` to `justification` in proposal details page votes table. #583 
- [x] Rename `Submit Time` to `Time` in proposal details page votes table. #583 
- [x] Rename `Voter` to `Member` in proposal details page votes table. #583 
- [x] ~Instead of showing the voter address, if available, display the member metadata in the votes table.~
